### ISSUE TITLE
DScribe imports annotations from the wrong location

### ISSUE THREAD

**Issue by lberardelli** [prmr/DScribe#2]
After invoking dscribe, the test class(es) associated with the focal method(s) import DScribe annotations from the wrong location. 

![Example_Image](https://user-images.githubusercontent.com/26488145/154563858-8d89bb01-2405-4a51-83a7-132585c88fd1.png)

**Comment by lberardelli** [comment]
This issue is not a problem with DScribe, but a problem with me. The imports and package declaration in the template.java are exactly the ones that get copied over during test generation. Might be nice to have that info in the README, but this is user error.

![Screen Shot 2022-02-22 at 4 55 31 PM](https://user-images.githubusercontent.com/26488145/155226185-28c5de77-3626-443e-81f2-a9b123d82ee3.png)

**Comment by AlexaHernandez** [comment]
Good point. This should definitely be in the README. I'll add it and close this issue.
